nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']  # React frontend URL
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600  # Cache preflight request for 1 hour
    paths:
        '^/api/':  # Apply CORS for API routes
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
